sonar.projectKey=shopify-clone-frontend
sonar.projectName=Shopify Clone - Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/environments/**
sonar.javascript.lcov.reportPaths=coverage/shopify-clone-frontend/lcov.info
sonar.sourceEncoding=UTF-8
